name: epandu
description: ePandu app.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## Online
  xml2json: ^4.2.0
  http: ^0.12.2
  firebase_messaging: ^7.0.0

  ## Widgets
  shimmer: ^1.1.1
  flushbar: ^1.10.4
  cupertino_icons: ^0.1.3
  flutter_custom_clippers: ^1.1.1
  datetime_picker_formfield: ^1.0.0
  transparent_image: ^1.0.0
  flutter_rating_bar: ^3.0.1+1
  country_code_picker: ^1.4.0
  badges: ^1.1.1
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  expandable: ^4.1.4
  image_picker: ^0.6.7+4
  image_cropper: ^1.2.3
  camera: ^0.5.8+5
  webview_flutter: ^0.3.22+1

  ## Tools
  intl: ^0.16.0
  provider: ^4.3.2+2
  geolocator: ^6.0.0+4
  geocoder: ^0.2.1
  url_launcher: ^5.5.3
  map_launcher: ^0.12.2
  flutter_svg: ^0.18.1
  app_settings: ^4.0.3
  path_provider: ^1.6.14
  shared_preferences: ^0.5.10
  device_info: ^0.4.2+7
  package_info: ^0.4.3
  flutter_screenutil: ^2.3.1
  flutter_spinkit: ^4.1.2+1
  random_color: ^1.0.5
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  google_fonts: ^1.1.0
  json_annotation: ^3.0.1
  html_unescape: ^1.0.2
  auto_route: ^0.6.7
  validators: ^2.0.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.4.1
  hive_generator: ^0.7.1
  build_runner:
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.8.0
  flutter_native_splash: ^0.1.9
  auto_route_generator: ^0.6.8

flutter_launcher_name:
  name: 'ePandu'

flutter_icons:
  android: true
  ios: true
  image_path_android: 'assets/icon/android-icon.png'
  image_path_ios: 'assets/icon/ios-icon.png'

flutter_native_splash:
  image: assets/splash/splash.png
  color: "ffcd0e"
  android_disable_fullscreen: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/en.json
    - assets/lang/ms.json

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.otf
        - asset: assets/fonts/MYRIADPRO-BOLD.otf
          weight: 700

    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyCustomIcons.ttf
