name: epandu
description: ePandu app.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  xml2json: ^4.0.0
  cupertino_icons: ^0.1.2
  path_provider: ^1.4.2
  shared_preferences: ^0.5.4+5
  device_info: ^0.4.1+1
  flutter_screenutil: ^0.6.1
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
