name: epandu
description: ePandu app.

version: 6.1.8+10

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## Online
  xml2json: ^5.3.2
  http: ^0.13.5
  # firebase_messaging: ^11.4.1

  ## Widgets
  shimmer: ^2.0.0
  another_flushbar: ^1.12.29
  cupertino_icons: ^1.0.5
  flutter_custom_clippers: ^2.1.0
  datetime_picker_formfield: ^2.0.1
  transparent_image: ^2.0.0
  flutter_rating_bar: ^4.0.1
  country_code_picker: ^2.0.2
  badges: ^3.0.2
  qr_flutter: ^4.0.0
  # barcode_scan: ^3.0.1
  # qr_code_scanner: ^1.0.1
  expandable: ^5.0.1
  image_picker: ^0.8.6+1
  image_cropper: ^3.0.1
  camera: ^0.10.3
  webview_flutter: ^4.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  photo_view: ^0.13.0
  flutter_linkify: ^5.0.2
  readmore: ^2.2.0
  # smart_select: ^4.3.2

  ## Tools
  intl: ^0.17.0
  provider: ^6.0.5
  geolocator: ^9.0.2
  flutter_geocoder: ^0.2.2-nullsafety
  url_launcher: ^6.1.9
  map_launcher: ^2.5.0
  flutter_svg: ^0.23.0+1
  app_settings: ^4.2.0
  path_provider: ^2.0.12
  shared_preferences: ^2.0.17
  device_info: ^2.0.3
  package_info: ^2.0.2
  flutter_screenutil: ^5.6.1
  flutter_spinkit: ^5.1.0
  random_color: ^1.0.6-nullsafety
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^4.0.3
  json_annotation: ^4.6.0
  html_unescape: ^2.0.0
  auto_route: ^4.2.1
  string_validator: ^0.3.0
  flutter_widget_from_html: ^0.9.1
  supercharged: ^2.1.1
  # firebase_core: ^1.17.1
  # firebase_analytics: ^6.2.0
  # firebase_crashlytics: ^0.2.3+1
  share: ^2.0.4
  native_pdf_view: ^6.0.0+1
  printing: ^5.6.5

  #chat
  rxdart: ^0.27.7
  socket_io_client: ^2.0.1
  sqflite: ^2.2.4+1
  uuid: ^3.0.7
  get: ^4.6.5
  video_player: ^2.5.1
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  file_picker: ^4.6.1
  open_file: ^3.2.1
  audio_session: ^0.1.13
  bubble: ^1.2.1
  full_screen_image_null_safe: ^2.0.0
  flutter_local_notifications: ^12.0.4
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  jumping_dot: ^0.0.4
  scrollable_positioned_list: ^0.3.5
  flutter_slidable: ^2.0.0
  emoji_picker_flutter: ^1.5.2
  flutter_sound_platform_interface: ^9.2.13
  native_pdf_renderer: ^5.0.0+1
  swipe_to: ^1.0.2
  flutter_easyloading: ^3.0.5
  flutter_typeahead: ^4.3.3
  form_builder_validators: ^8.4.0
  sentry_flutter: ^6.20.1
  google_maps_flutter: ^2.2.3
  flutter_form_builder: ^7.7.0
  dotted_border: ^2.0.0+1
  scroll_app_bar: ^2.0.0
  dropdown_search: ^5.0.5
  flick_video_player: ^0.5.0
  visibility_detector: ^0.4.0+2

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner.git
      ref: flutter-beta

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.0+1
  auto_route_generator: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android-icon.png"
  image_path_ios: "assets/icon/ios-icon.png"

flutter_native_splash:
  image: assets/splash/splash.png
  color: "ffcd0e"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/menu/
    - assets/lang/en.json
    - assets/lang/ms.json
    - assets/svg/

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.otf
        - asset: assets/fonts/MYRIADPRO-BOLD.otf
          weight: 700

    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyCustomIcons.ttf
