name: epandu
description: ePandu app.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependency_overrides:
  dartx: ^0.4.0

dependencies:
  flutter:
    sdk: flutter

  ## Online
  xml2json: ^4.1.1
  http: ^0.12.0+4
  firebase_messaging: ^6.0.16

  ## Widgets
  shimmer: ^1.0.1
  flushbar: ^1.10.4
  cupertino_icons: ^0.1.2
  flutter_custom_clippers: ^1.1.0
  datetime_picker_formfield: ^1.0.0
  transparent_image: ^1.0.0
  flutter_rating_bar: ^3.0.1+1
  country_code_picker: ^1.3.9
  badges: ^1.1.1
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  expandable: ^4.1.4
  image_picker: ^0.6.7+2
  image_cropper: ^1.2.3
  camera: ^0.5.8+2

  ## Tools
  intl: ^0.16.0
  provider: ^4.0.4
  geolocator: ^5.3.1
  geocoder: ^0.2.1
  url_launcher: ^5.4.1
  map_launcher: ^0.4.1
  app_settings: ^3.0.0+1
  path_provider: ^1.6.10
  shared_preferences: ^0.5.7+3
  device_info: ^0.4.2+1
  package_info: ^0.4.1
  flutter_screenutil: ^1.1.0
  flutter_spinkit: ^4.1.1+1
  random_color: ^1.0.3
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  google_fonts: ^0.3.2
  json_annotation: ^3.0.1
  html_unescape: ^1.0.1+3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.3
  hive_generator: ^0.7.0
  build_runner:
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.4

flutter_launcher_name:
  name: 'ePandu'

flutter_icons:
  android: true
  ios: true
  image_path_android: 'assets/icon/android-icon.png'
  image_path_ios: 'assets/icon/ios-icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/en.json
    - assets/lang/ms.json

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.otf
        - asset: assets/fonts/MYRIADPRO-BOLD.otf
          weight: 700

    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyCustomIcons.ttf
