name: epandu
description: ePandu app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 6.2.1+16

environment:
  sdk: ">=3.0.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ## Online
  xml2json:
  http:
  # firebase_messaging: ^11.4.1

  ## Widgets
  shimmer:
  another_flushbar:
  cupertino_icons:
  flutter_custom_clippers:
  datetime_picker_formfield:
  transparent_image:
  flutter_rating_bar:
  country_code_picker:
  badges:
  qr_flutter:
  # barcode_scan: ^3.0.1
  # qr_code_scanner: ^1.0.1
  expandable:
  image_picker:
  image_cropper:
  camera:
  webview_flutter:
  webview_flutter_android:
  webview_flutter_wkwebview:
  qr_code_scanner:
  quiver:
  carousel_slider:
  smooth_page_indicator:
  photo_view:
  flutter_linkify:
  readmore:
    # smart_select: ^4.3.2

    ## Tools
  intl:
  provider:
  geolocator:
  geocoder:
    git:
      url: https://github.com/nguyenxdat/flutter_geocoder.git
      ref: 443b875d8ec80ce525cc6e8f17dfbbbbe7fa3028
  url_launcher:
  map_launcher:
  flutter_svg:
  app_settings:
  path_provider:
  shared_preferences:
  device_info:
  package_info:
  flutter_screenutil:
  flutter_spinkit:
  random_color:
  hive:
  hive_flutter:
  google_fonts:
  json_annotation:
  html_unescape:
  auto_route:
  string_validator:
  flutter_widget_from_html:
  supercharged:
  # firebase_core: ^1.17.1
  # firebase_analytics: ^6.2.0
  # firebase_crashlytics: ^0.2.3+1
  share:
  native_pdf_view:
  printing: ^5.11.1

  #chat
  rxdart:
  socket_io_client:
  sqflite:
  uuid:
  get:
  video_player:
  flutter_sound:
  permission_handler:
  file_picker:
  open_file:
  audio_session:
  bubble:
  full_screen_image_null_safe:
  flutter_local_notifications:
  firebase_core:
  firebase_messaging:
  jumping_dot:
  scrollable_positioned_list:
  flutter_slidable:
  emoji_picker_flutter:
  flutter_sound_platform_interface:
  native_pdf_renderer:
  swipe_to:
  flutter_easyloading:
  flutter_typeahead:
  form_builder_validators:
  sentry_flutter:
  google_maps_flutter:
  flutter_form_builder:
  dotted_border:
  #scroll_app_bar:
  dropdown_search:
  flick_video_player:
  visibility_detector:
  cached_network_image:
  path:
  sentry_sqflite:

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner.git
      ref: flutter-beta
  package_info_plus_windows:
    git:
      url: https://github.com/joshua1996/package_info_plus_windows.git
      ref: main # branch name
  photo_view: 0.14.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  hive_generator:
  build_runner:
  flutter_launcher_icons:
  flutter_native_splash:
  auto_route_generator:
  flutter_lints:

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android-icon.png"
  image_path_ios: "assets/icon/ios-icon.png"

flutter_native_splash:
  image: assets/splash/splash.png
  color: "ffcd0e"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/menu/
    - assets/lang/en.json
    - assets/lang/ms.json
    - assets/svg/

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.otf
        - asset: assets/fonts/MYRIADPRO-BOLD.otf
          weight: 700

    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyCustomIcons.ttf
