name: epandu
description: ePandu app.

version: 2.0.168+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## Online
  xml2json: ^5.3.2 
  http: ^0.13.4
  firebase_messaging: ^11.4.1 

  ## Widgets
  shimmer: ^2.0.0
  another_flushbar: ^1.10.29
  cupertino_icons: ^1.0.4
  flutter_custom_clippers: ^2.0.0 
  datetime_picker_formfield: ^2.0.0
  transparent_image: ^2.0.0
  flutter_rating_bar: ^4.0.1 
  country_code_picker: ^2.0.2 
  badges: ^2.0.3
  qr_flutter: ^4.0.0 
  # barcode_scan: ^3.0.1
  qr_code_scanner: ^1.0.0
  expandable: ^5.0.1 
  image_picker: ^0.8.5+3 
  image_cropper: ^2.0.3 
  camera: ^0.9.7+1
  webview_flutter: ^3.0.4 
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2 
  photo_view: ^0.13.0 
  flutter_linkify: ^5.0.2 
  readmore: ^2.1.0 
  # smart_select: ^4.3.2

  ## Tools
  intl: ^0.17.0 
  provider: ^6.0.3
  geolocator: ^8.2.1 
  flutter_geocoder: ^0.2.2-nullsafety 
  url_launcher: ^6.1.2 
  map_launcher: ^2.2.3 
  flutter_svg: ^0.23.0+1 
  app_settings: ^4.1.6 
  path_provider: ^2.0.10 
  shared_preferences: ^2.0.15 
  device_info: ^2.0.3 
  package_info: ^2.0.2 
  flutter_screenutil: ^5.5.3+2 
  flutter_spinkit: ^5.1.0
  random_color: ^1.0.6-nullsafety
  hive: ^2.2.1 
  hive_flutter: ^1.1.0 
  google_fonts: ^3.0.1 
  json_annotation: ^4.5.0
  html_unescape: ^2.0.0 
  auto_route: ^4.0.1 
  string_validator: ^0.3.0 
  flutter_widget_from_html: ^0.8.5 
  supercharged: ^2.1.1 
  firebase_core: ^1.17.1 
  # firebase_analytics: ^6.2.0
  # firebase_crashlytics: ^0.2.3+1
  share: ^2.0.4 
  native_pdf_view: ^6.0.0+1 
  printing: ^5.6.5 

  #chat
  rxdart: ^0.27.4 
  socket_io_client: ^1.0.2 
  sqflite: ^2.0.2+1
  uuid: ^3.0.6 
  flutter_typeahead: ^4.0.0 
  sentry_flutter:
  scroll_app_bar:
  flutter_form_builder:
  form_builder_validators:
  google_maps_flutter:
  flutter_map:
  latlong2:
  huawei_map:
  dotted_border:
  dropdown_search:
  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0 
  hive_generator: ^1.1.3
  build_runner: ^2.1.11 
  flutter_launcher_icons: ^0.9.2 
  flutter_native_splash: ^2.2.0+1 
  auto_route_generator: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path_android: 'assets/icon/android-icon.png'
  image_path_ios: 'assets/icon/ios-icon.png'

flutter_native_splash:
  image: assets/splash/splash.png
  color: "ffcd0e"
  android_disable_fullscreen: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/menu/
    - assets/lang/en.json
    - assets/lang/ms.json

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.otf
        - asset: assets/fonts/MYRIADPRO-BOLD.otf
          weight: 700

    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyCustomIcons.ttf