name: epandu
description: ePandu app.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## Online
  xml2json: ^5.3.1
  http: ^0.13.3
  firebase_messaging: ^10.0.3

  ## Widgets
  shimmer: ^2.0.0
  another_flushbar: ^1.10.23
  cupertino_icons: ^1.0.3
  flutter_custom_clippers: ^2.0.0
  datetime_picker_formfield: ^2.0.0
  transparent_image: ^2.0.0
  flutter_rating_bar: ^4.0.0
  country_code_picker: ^2.0.2
  badges: ^2.0.1
  qr_flutter: ^4.0.0
  # barcode_scan: ^3.0.1
  qr_code_scanner: ^0.5.1
  expandable: ^5.0.1
  image_picker: ^0.8.1+3
  image_cropper: ^1.4.1
  camera: ^0.8.1+3
  webview_flutter: ^2.0.9
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  photo_view: ^0.12.0
  flutter_linkify: ^5.0.2
  readmore: ^2.1.0
  # smart_select: ^4.3.2

  ## Tools
  intl: ^0.17.0
  provider: ^5.0.0
  geolocator: ^7.2.0+1
  flutter_geocoder: ^0.2.2-nullsafety
  url_launcher: ^6.0.9
  map_launcher: ^2.1.1
  flutter_svg: ^0.22.0
  app_settings: ^4.1.1
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  device_info: ^2.0.2
  package_info: ^2.0.2
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.0.0
  random_color: ^1.0.6-nullsafety
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  google_fonts: ^2.1.0
  json_annotation: ^4.0.1
  html_unescape: ^2.0.0
  auto_route: ^2.2.0
  string_validator: ^0.3.0
  flutter_widget_from_html: ^0.6.1
  supercharged: ^2.0.0
  firebase_core: ^1.3.0
  # firebase_analytics: ^6.2.0
  # firebase_crashlytics: ^0.2.3+1
  share: ^2.0.4
  native_pdf_view: ^4.1.0
  printing: ^5.4.3

  #chat
  rxdart: ^0.27.1
  socket_io_client: ^1.0.1
  sqflite: ^2.0.0+3
  uuid: ^3.0.4
  flutter_typeahead: ^3.1.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
  hive_generator: ^1.1.0
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  auto_route_generator: ^2.1.0

flutter_icons:
  android: true
  ios: true
  image_path_android: 'assets/icon/android-icon.png'
  image_path_ios: 'assets/icon/ios-icon.png'

flutter_native_splash:
  image: assets/splash/splash.png
  color: "ffcd0e"
  android_disable_fullscreen: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/en.json
    - assets/lang/ms.json

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.otf
        - asset: assets/fonts/MYRIADPRO-BOLD.otf
          weight: 700

    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyCustomIcons.ttf