name: epandu
description: ePandu app.

version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## Online
  xml2json: ^4.2.0
  http: ^0.12.2
  firebase_messaging: ^7.0.3

  ## Widgets
  shimmer: ^1.1.2
  flushbar: ^1.10.4
  cupertino_icons: ^1.0.0
  flutter_custom_clippers: ^1.1.1
  datetime_picker_formfield: ^1.0.0
  transparent_image: ^1.0.0
  flutter_rating_bar: ^3.2.0
  country_code_picker: ^1.4.0
  badges: ^1.1.4
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  expandable: ^4.1.4
  image_picker: ^0.6.7+12
  image_cropper: ^1.3.1
  camera: ^0.5.8+11
  webview_flutter: ^1.0.7
  carousel_slider: ^2.3.1
  smooth_page_indicator: ^0.2.0
  photo_view: ^0.10.3
  # flutter_linkify: ^4.0.2
  # smart_select: ^4.3.2

  ## Tools
  intl: ^0.16.1
  provider: ^4.3.2+2
  geolocator: ^6.1.7
  geocoder: ^0.2.1
  url_launcher: ^5.7.10
  map_launcher: ^0.12.2
  flutter_svg: ^0.19.1
  app_settings: ^4.0.4
  path_provider: ^1.6.24
  shared_preferences: ^0.5.12+4
  device_info: ^1.0.0
  package_info: ^0.4.3+2
  flutter_screenutil: ^3.2.0
  flutter_spinkit: ^4.1.2+1
  random_color: ^1.0.5
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  google_fonts: ^1.1.0
  json_annotation: ^3.1.0
  html_unescape: ^1.0.2
  auto_route: ^0.6.9
  string_validator: ^0.1.4
  flutter_widget_from_html: ^0.5.1+4
  supercharged: ^1.11.1
  firebase_core: ^0.5.2+1
  # firebase_analytics: ^6.2.0
  # firebase_crashlytics: ^0.2.3+1

  #chat
  rxdart: ^0.24.1
  socket_io_client: ^0.9.11
  sqflite: ^1.3.1+1
  uuid: ^2.2.2
  flutter_typeahead: ^1.8.8

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0
  hive_generator: ^0.8.2
  build_runner:
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9
  auto_route_generator: ^0.6.10

flutter_launcher_name:
  name: 'ePandu'

flutter_icons:
  android: true
  ios: true
  image_path_android: 'assets/icon/android-icon.png'
  image_path_ios: 'assets/icon/ios-icon.png'

flutter_native_splash:
  image: assets/splash/splash.png
  color: "ffcd0e"
  android_disable_fullscreen: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/en.json
    - assets/lang/ms.json

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.otf
        - asset: assets/fonts/MYRIADPRO-BOLD.otf
          weight: 700

    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyCustomIcons.ttf