/// Flutter icons MyCustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyCustomIcons
///      fonts:
///       - asset: fonts/MyCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyCustomIcons {
  MyCustomIcons._();

  static const _kFontFam = 'MyCustomIcons';

  static const IconData label_percent_outline = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData gift_outline = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData face_recognition = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData scan_helper = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData chat_processing_outline = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData account_circle_outline = const IconData(0xe805, fontFamily: _kFontFam);
}
