/// Flutter icons MyCustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyCustomIcons
///      fonts:
///       - asset: fonts/MyCustomIcons.ttf
///
///
///
library;
import 'package:flutter/widgets.dart';

class MyCustomIcons {
  MyCustomIcons._();

  static const _kFontFam = 'MyCustomIcons';

  static const IconData labelPercentOutline =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData giftOutline = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData faceRecognition =
      IconData(0xe802, fontFamily: _kFontFam);
  static const IconData scanHelper = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData chatProcessingOutline =
      IconData(0xe804, fontFamily: _kFontFam);
  static const IconData accountCircleOutline =
      IconData(0xe805, fontFamily: _kFontFam);
  static const IconData touchMeIcon = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData inboxIcon = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData accountIcon = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData giftIcon = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData homeIcon = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData idIcon = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData inviteIcon = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData promoIcon = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData scanIcon = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData vClubIcon = IconData(0xe819, fontFamily: _kFontFam);
}
