import 'package:auto_route/auto_route.dart';
import 'package:epandu/router.gr.dart';

@AutoRouterConfig(
  replaceInRouteName: 'Page,Route',
)
class AppRouter extends $AppRouter {
  @override
  RouteType get defaultRouteType => const RouteType.material();
  @override
  final List<AutoRoute> routes = [
    AutoRoute(page: Authentication.page, path: '/', initial: true),
    AutoRoute(path: '/clientAccount', page: ClientAccount.page),
    AutoRoute(path: '/login', page: Login.page),
    AutoRoute(path: '/forgotPassword', page: ForgotPassword.page),
    AutoRoute(path: '/changePassword', page: ChangePassword.page),
    AutoRoute(path: '/registerMobile', page: RegisterMobile.page),
    AutoRoute(path: '/registerVerification', page: RegisterVerification.page),
    AutoRoute(path: '/registerForm', page: RegisterForm.page),
    AutoRoute(path: '/home', page: Home.page),
    AutoRoute(path: '/queueNumber', page: QueueNumber.page),
    AutoRoute(path: '/enrollment', page: Enrollment.page),
    AutoRoute(path: '/diEnrollment', page: DiEnrollment.page),
    AutoRoute(path: '/enrollConfirmation', page: EnrollConfirmation.page),
    AutoRoute(path: '/orderList', page: OrderList.page),
    AutoRoute(path: '/bankList', page: BankList.page),
    AutoRoute(path: '/paymentStatus', page: PaymentStatus.page),
    AutoRoute(path: '/kppCategory', page: KppCategory.page),
    AutoRoute(path: '/kppResult', page: KppResult.page),
    AutoRoute(path: '/kppExam', page: KppExam.page),
    AutoRoute(path: '/kppModule', page: KppModule.page),
    AutoRoute(path: '/pinActivation', page: PinActivation.page),
    AutoRoute(path: '/valueClub', page: ValueClub.page),
    AutoRoute(path: '/product', page: Product.page),
    AutoRoute(path: '/productList', page: ProductList.page),
    AutoRoute(path: '/cart', page: Cart.page),
    AutoRoute(path: '/cartItemEdit', page: CartItemEdit.page),
    AutoRoute(path: '/checkout', page: Checkout.page),
    AutoRoute(path: '/epanduCategory', page: EpanduCategory.page),
    AutoRoute(path: '/epanduCategory', page: EtestingCategory.page),
    AutoRoute(path: '/emergencyDirectory', page: EmergencyDirectory.page),
    AutoRoute(path: '/directoryList', page: DirectoryList.page),
    AutoRoute(path: '/directoryDetail', page: DirectoryDetail.page),
    AutoRoute(path: '/selectInstitute', page: SelectInstitute.page),
    AutoRoute(path: '/selectClass', page: SelectClass.page),
    AutoRoute(
        path: '/selectDrivingInstitute', page: SelectDrivingInstitute.page),
    AutoRoute(path: '/takeProfilePicture', page: TakeProfilePicture.page),
    AutoRoute(path: '/booking', page: Booking.page),
    AutoRoute(path: '/addBooking', page: AddBooking.page),
    AutoRoute(path: '/records', page: Records.page),
    AutoRoute(path: '/pay', page: Pay.page),
    AutoRoute(path: '/purchaseOrderList', page: PurchaseOrderList.page),
    AutoRoute(path: '/paymentHistory', page: PaymentHistory.page),
    AutoRoute(path: '/paymentHistoryDetail', page: PaymentHistoryDetail.page),
    AutoRoute(path: '/requestPickup', page: RequestPickup.page),
    AutoRoute(path: '/registeredCourse', page: RegisteredCourse.page),
    AutoRoute(
        path: '/registeredCourseDetail', page: RegisteredCourseDetail.page),
    AutoRoute(path: '/attendanceRecord', page: AttendanceRecord.page),
    AutoRoute(path: '/attendanceTab', page: AttendanceTab.page),
    AutoRoute(path: '/promotions', page: Promotions.page),
    AutoRoute(path: '/profile', page: Profile.page),
    AutoRoute(path: '/profileTab', page: ProfileTab.page),
    AutoRoute(path: '/updateProfile', page: UpdateProfile.page),
    AutoRoute(path: '/registerUserToDi', page: RegisterUserToDi.page),
    AutoRoute(path: '/identityBarcode', page: IdentityBarcode.page),
    AutoRoute(path: '/enrolmentInfo', page: EnrolmentInfo.page),
    AutoRoute(path: '/enrolmentInfoDetail', page: EnrolmentInfoDetail.page),
    AutoRoute(path: '/inbox', page: Inbox.page),
    AutoRoute(path: '/invite', page: Invite.page),
    AutoRoute(path: '/airtimeTransaction', page: AirtimeTransaction.page),
    AutoRoute(path: '/airtimeBillDetail', page: AirtimeBillDetail.page),
    AutoRoute(path: '/airtimeSelection', page: AirtimeSelection.page),
    AutoRoute(path: '/billTransaction', page: BillTransaction.page),
    AutoRoute(path: '/billDetail', page: BillDetail.page),
    AutoRoute(path: '/billSelection', page: BillSelection.page),
    AutoRoute(path: '/merchantList', page: MerchantList.page),
    AutoRoute(path: '/chatHome', page: ChatHome.page),
    AutoRoute(path: '/termsAndCondition', page: TermsAndCondition.page),
    AutoRoute(path: '/fpxPaymentOption', page: FpxPaymentOption.page),
    AutoRoute(path: '/imageViewer', page: ImageViewer.page),
    AutoRoute(path: '/webview', page: Webview.page),
    AutoRoute(path: '/scan', page: Scan.page),
    AutoRoute(path: '/readMore', page: ReadMore.page),
    AutoRoute(path: '/viewPdf', page: ViewPdf.page),
    AutoRoute(path: '/comingSoon', page: ComingSoon.page),
    AutoRoute(path: '/checkInSlip', page: CheckInSlip.page),
    AutoRoute(path: '/multilevel', page: Multilevel.page),
    AutoRoute(path: '/merchantProfile', page: MerchantProfile.page),
    AutoRoute(page: MenuRoute.page),
    AutoRoute(page: ElearningRoute.page),
    AutoRoute(page: CreateFavouriteRoute.page),
    AutoRoute(page: FavourieMapRoute.page),
    AutoRoute(page: CreateFuelRoute.page),
    AutoRoute(page: CreateServiceCarRoute.page),
    AutoRoute(page: FavouritePlaceListRoute.page),
    AutoRoute(page: PhotoViewRoute.page),
    AutoRoute(page: EditFavouritePlaceRoute.page),
    AutoRoute(page: FuelMapRoute.page),
    AutoRoute(page: ExpFuelListRoute.page),
    AutoRoute(page: EditExpFuelRoute.page),
    AutoRoute(page: PickupHistory.page),
    AutoRoute(page: BriefListRoute.page),
    AutoRoute(page: BriefVideoRoute.page),
    AutoRoute(path: '/roomList', page: RoomList.page),
    AutoRoute(page: ProductShowRoute.page),
  ];
}
